pref("extensions.zotero.greenfrog.enable", true);
pref("extensions.zotero.greenfrog.enable1", false);
pref("extensions.zotero.greenfrog.input", "This is input");
pref("extensions.zotero.greenfrog.secretkey", "");
// 期刊缩写
pref("extensions.zotero.greenfrog.update.empty.extra", false);
pref("extensions.zotero.greenfrog.add.update", false);
pref("extensions.zotero.greenfrog.update.abbr", true);
pref("extensions.zotero.greenfrog.update.abbr.dot", true);
pref("extensions.zotero.greenfrog.en.abbr", true);
pref("extensions.zotero.greenfrog.ch.abbr", true);

// 学校期刊分类
pref("extensions.zotero.greenfrog.swufe", false);
pref("extensions.zotero.greenfrog.cufe", false);
pref("extensions.zotero.greenfrog.uibe", false);
pref("extensions.zotero.greenfrog.sdufe", false);
pref("extensions.zotero.greenfrog.xdu", false);
pref("extensions.zotero.greenfrog.swjtu", false);
pref("extensions.zotero.greenfrog.ruc", false);
pref("extensions.zotero.greenfrog.xmu", false);
pref("extensions.zotero.greenfrog.sjtu", false);
pref("extensions.zotero.greenfrog.fdu", false);
pref("extensions.zotero.greenfrog.hhu", false);
pref("extensions.zotero.greenfrog.scu", false);
pref("extensions.zotero.greenfrog.cqu", false);
pref("extensions.zotero.greenfrog.nju", false);
pref("extensions.zotero.greenfrog.xju", false);
pref("extensions.zotero.greenfrog.cug", false);
pref("extensions.zotero.greenfrog.cju", false);
pref("extensions.zotero.greenfrog.zju", false);
pref("extensions.zotero.greenfrog.njau.core", true);
pref("extensions.zotero.greenfrog.njau.high.quality", true);
// 自定义数据集
pref("extensions.zotero.greenfrog.clsci", false);
pref("extensions.zotero.greenfrog.ami", false);
pref("extensions.zotero.greenfrog.nssf", false);


// 影响因子
pref("extensions.zotero.greenfrog.jcr.qu", true);
pref("extensions.zotero.greenfrog.basic", false);
pref("extensions.zotero.greenfrog.updated", true);
pref("extensions.zotero.greenfrog.sci.if", true);
pref("extensions.zotero.greenfrog.sci.if5", true);
pref("extensions.zotero.greenfrog.ei", true);
pref("extensions.zotero.greenfrog.chjcscd", true);
pref("extensions.zotero.greenfrog.pku.core", true);
pref("extensions.zotero.greenfrog.nju.core", false);
pref("extensions.zotero.greenfrog.sci.core", false);
pref("extensions.zotero.greenfrog.ssci", false);
pref("extensions.zotero.greenfrog.ajg", false);
pref("extensions.zotero.greenfrog.utd24", false);
pref("extensions.zotero.greenfrog.ft50", false);
pref("extensions.zotero.greenfrog.ccf", false);
pref("extensions.zotero.greenfrog.fms", false);
pref("extensions.zotero.greenfrog.jci", false);
pref("extensions.zotero.greenfrog.ahci", false);
pref("extensions.zotero.greenfrog.sciwarn", false);
pref("extensions.zotero.greenfrog.com.if", true);
pref("extensions.zotero.greenfrog.agg.if", true);
pref("extensions.zotero.greenfrog.summary", false);

pref("extensions.zotero.greenfrog.bold.star", true);
pref("extensions.zotero.greenfrog.remove.bold", true);
pref("extensions.zotero.greenfrog.remove.star", true);
pref("extensions.zotero.greenfrog.remove.bold.star", true);
pref("extensions.zotero.greenfrog.chang.author.case", true);
pref("extensions.zotero.greenfrog.swap.author", true);
pref("extensions.zotero.greenfrog.chang.title", true);
pref("extensions.zotero.greenfrog.chang.pub.title", true);
pref("extensions.zotero.greenfrog.chang.pub.title.case", true);
pref("extensions.zotero.greenfrog.item.title.find.replace", true);
pref("extensions.zotero.greenfrog.show.profile.dir", true);
pref("extensions.zotero.greenfrog.show.data.dir", true);
pref("extensions.zotero.greenfrog.sep1", true);
pref("extensions.zotero.greenfrog.sep2", true);

// 快捷键设置
pref("extensions.zotero.greenfrog.shortcut.title.sentence", true);
pref("extensions.zotero.greenfrog.shortcut.input.title.sentence", 'T');
pref("extensions.zotero.greenfrog.shortcut.publication.title.case", true);
pref("extensions.zotero.greenfrog.shortcut.input.publication.title.case", 'U');
pref("extensions.zotero.greenfrog.shortcut.data.dir", true);
pref("extensions.zotero.greenfrog.shortcut.input.data.dir", 'D');
pref("extensions.zotero.greenfrog.shortcut.profile.dir", true);
pref("extensions.zotero.greenfrog.shortcut.input.profile.dir", 'P');
